### ISSUE TITLE
Error reading clients.yml

### ISSUE THREAD

**Issue by genetzhs** [DaKnOb/eldim#11]
Example File clients.yml
-
  name: "mail.example.com"
  ipv4:
    - "192.0.2.10"

returns FATA[0000] Invalid configuration: Failed to validate Clients File: IP "192.0.2.10" in host "mail.example.com" (1) is not an IPv4 Address 

Example File clients.yml
-
  name: "mail.example.com"
  ipv4:
    - "192.0.2.[1-9]"

works.

It seems that parsing of the file clients.yml does not recognize ips that are above xxx.xxx.xxx.9

**Comment by daknob** [comment]
Thanks for the report! This is a bug that was introduced in the latest release of `eldim` where a bad regular expression failed if the IPv4 address contained more than one digit in the last octet.

The bug has been addressed by correcting the regular expression.
